### ISSUE TITLE
marketing experiment tracking

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#82]
- [x] research how to properly track marketing experiments
- [x] build a decision matrix listing all of the important features you have identified
- [x] list all of the relevant tools and services you have found
- [x] compare lists when you are both finished
- [x] pitch bennett on your top 2-3 choices
