### ISSUE TITLE
Explore free trials for experiment tracking software 

### ISSUE THREAD

**Issue by bennett-brown** [Miralaw/thistoo-marketing#86]
- [ ] choose 2 services each
- [ ] access free trials
- [ ] integrate all of our marketing campaigns and data
- [ ] determine most effective solution
