### ISSUE TITLE
Build Amp pages

### ISSUE THREAD

**Issue by Henri-K** [Miralaw/thistoo-marketing#9]
https://coderwall.com/p/wpyasq/how-to-create-an-amp-page-for-your-dynamic-content-in-rails
https://github.com/ampproject/amphtml

- [x] mime type and framework implementation
- [x] basic formatting
- [x] scrubber implementation for existing partials
- [x] rebuild styling to fit within size constraints
- [x] include amp sidebar
- [x] test on staging
- [x] fix any issues
